version: "3.9"

services:

  # --------------------
  # Infrastructure
  # --------------------
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      # Per-listener JAAS config (avoids global JAAS file that breaks ZK connection)
      KAFKA_LISTENER_NAME_SASL__PLAINTEXT_PLAIN_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";'

      KAFKA_OPTS: "-Dzookeeper.sasl.client=false"

      KAFKA_ZOOKEEPER_SET_ACL: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --------------------
  # API Gateway
  # --------------------
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api-gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - identity
      - tenant
      - notification
      - institution

  # --------------------
  # Application Services
  # --------------------
  identity:
    image: identity-service:latest
    environment:
      AWS_PROFILE: cognito-role
      PERMISSION_CACHE_DEBUG: 1
    container_name: identity
    expose:
      - "8080"
    env_file:
      - ../Identity-Service/identity-service/.env
    depends_on:
      - postgres
      - kafka
      - zookeeper
    volumes:
      - ~/.aws:/root/.aws:ro
  tenant:
    image: tenant-service:latest
    environment:
      AWS_PROFILE: cognito-role
      AWS_REGION: ap-south-1
    container_name: tenant
    expose:
      - "8080"
    env_file:
      - ../Tenant-Service/tenant-service/.env
    depends_on:
      - postgres
      - kafka
      - zookeeper
    volumes:
      - ~/.aws:/root/.aws:ro
  notification:
    image: notification-service:latest
    environment:
      AWS_PROFILE: ses-notification
    container_name: notification
    expose:
      - "8080"
    env_file:
      - ../Notification-Service/notification-service/.env
    depends_on:
      - postgres
      - kafka
      - zookeeper
    volumes:
      - ~/.aws:/root/.aws:ro
  institution:
    image: institution-core-service:latest
    environment:
      AWS_PROFILE: cognito-role
      AWS_REGION: ap-south-1
    container_name: institution
    expose:
      - "8080"
    env_file:
      - ../Institution-Core-Service/institution-core-service/.env
    depends_on:
      - postgres
      - kafka
      - zookeeper
    volumes:
      - ~/.aws:/root/.aws:ro
  
  media:
    image: media-service:latest
    environment:
      AWS_PROFILE: s3role
      AWS_REGION: ap-south-1
    container_name: media
    expose:
      - "8080"
    env_file:
      - ../lms-mhc.media-management/lms-mhc-media-management/.env
    depends_on:
      - postgres
      - kafka
      - zookeeper
    volumes:
      - ~/.aws:/root/.aws:ro

volumes:
  pg_data:
